import Head from "next/head";
import { useEffect, useState } from "react";
import MainSection from "../components/Sections/MainSection";
import Navbar from "../components/Navbar";


export default function Home() {
  const [fullData, setFullData] = useState()
  let startUrl = "https://api.themoviedb.org/3/";
  let apiKey = "1e14fdee0ea09ca708c0b3a27257ede2";
  

  useEffect((startUrl,apiKey) =>{
    async function dataRequest(){
      let url = "".concat(startUrl, "movie/popular?api_key=",apiKey);
      const response = await fetch(url);
      
      setFullData(await response.json());
  
    }

    dataRequest();
    
    
    


  }, []);

  for(let i=0; i<10; i++){
    try{
    console.log(fullData.results[i].title);
    }catch(e){

    }
  }
    
    

  
  
   


  return (
    <div>
      <Head>
        <title>TMDB Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
       
      <Navbar  data={fullData} />
      <MainSection />
    </div>
  );
}
