import Head from "next/head";
import Movies from "../components/Movies";
import Navbar from "../components/Navbar";


export default function Home() {
  return (
    <div>
      <Head>
        <title>TMDB Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Movies />
    </div>
  );
}
